2025-07-15 07:06:57 +0000 - dagster - DEBUG - __ASSET_JOB - ff389151-de32-4dc8-89f4-00b41776d891 - 253 - LOGS_CAPTURED - Started capturing logs in process (pid: 253).
2025-07-15 07:06:57 +0000 - dagster - DEBUG - __ASSET_JOB - ff389151-de32-4dc8-89f4-00b41776d891 - 253 - generate_asset_data - STEP_START - Started execution of step "generate_asset_data".
2025-07-15 07:06:58 +0000 - dagster - ERROR - __ASSET_JOB - ff389151-de32-4dc8-89f4-00b41776d891 - 253 - generate_asset_data - STEP_FAILURE - Execution of step "generate_asset_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "generate_asset_data"::

OSError: Cannot save file into a non-existent directory: '/workspace/dagster_pipeline/data_pipeline/data'

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/app/src/ingestion/dim_assets.py", line 27, in generate_asset_data
    df.to_csv('/workspace/dagster_pipeline/data_pipeline/data/asset.csv', mode='a', index=False)
  File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/usr/local/lib/python3.11/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")

